//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoServicesApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTableProd
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Venue { get; set; }
        public string StreetAdress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Music { get; set; }
        public string DressCode { get; set; }
        public string Age { get; set; }
        public string Cost { get; set; }
        public byte[] Flyer { get; set; }
        public string VideoUrl { get; set; }
        public string EventSpecials { get; set; }
    }
}
